# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97fc1e8c597ab8783ea721a56a799782a40d0c67a89b288cb8378c4573f1afd52e61f67fa517b6fc8a727a36eaad72160dc876bf1e6258d95a897b26abe5e9fa

test:
  secret_key_base: bcc2572e716b35dd6e9ba53198a88efa2513202b54b2f7fc920ce85369bd2b4955c93d954b1e7a9c70ed0148ad9ce0ffb2cfc27b41cd5543c8f688c7022b2d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
